name: Monolith App CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backAgent/**'
      - 'BackSimulation/**'
      - 'front/**'
      - 'Dockerfile'
      - 'docker_launcher.sh'
      - 'docker_nginx.conf'
      - 'app_deploy_test.yml'

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: siliataider/citymanager-app:latest
          context: . 
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-dockerize

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Render
      run: >
        curl -X POST -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' -d '' 
        https://api.render.com/deploy/srv-cmkfojta73kc73bmc4a0?key=8aIKnO5Qv_w

  test-server:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install Python dependencies
        run: |
          cd backAgent 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backAgent
          python -m pytest
