name: Java CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: cd BackSimulation && mvn -e clean package

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: siliataider/backsimulation:latest
        file: ./Dockerfile

    - name: Deploy to Render
      run: curl -X POST -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' -d '' https://api.render.com/deploy/srv-cmj4au6n7f5s73a7dvu0?key=a578AouEmQE