name: React CI/CD

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'front/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Render
      run: |
        curl -X POST \
          -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
          https://api.render.com/deploy/srv-cmik6u21hbls738fd6cg?key=B15f7SbU19w
  
  check-deployment:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Check Deployment Status on Render
      run: python backAgent/tests/check_deployment_status.py
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        SERVICE_ID: 'srv-cmik6u21hbls738fd6cg'

  test-server:
    runs-on: ubuntu-latest
    needs: check-deployment

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        cd backAgent 
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd front
        python -m pytest
